[workspace]
members = [
  "utils",
  "math",
  "crypto",
  "common",
  "fri",
  "prover",
  "verifier",
  "examples"
]

[profile.release]
codegen-units = 1
lto = true

[profile.bench]
codegen-units = 1
lto = true
