edition = "2021"
array_width = 80
attr_fn_like_width = 80
chain_width = 80
comment_width = 100
condense_wildcard_suffixes = true
fn_call_width = 80
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
newline_style = "Unix"
match_block_trailing_comma = true
single_line_if_else_max_width = 60
single_line_let_else_max_width = 60
struct_lit_width = 40
struct_variant_width = 40
use_field_init_shorthand = true
use_try_shorthand = true